datafold_demo:

  target: dev
  outputs:
    dev:
      type: duckdb
      schema: dev_sung
      path: 'datafold_demo.duckdb'
      threads: 16

    prod:
      type: duckdb
      schema: prod_sung
      path: 'datafold_demo.duckdb'
      threads: 16