datafold_demo:

  target: dev
  outputs:
    dev:
      type: duckdb
      schema: development
      path: 'datafold_demo.duckdb'
      threads: 16

    prod:
      type: duckdb
      schema: production
      path: 'datafold_demo.duckdb'
      threads: 16